### ISSUE TITLE
Raw HTML omitted

### ISSUE THREAD

**Issue by izgzhen** [zopieux/pycmarkgfm#1]
```
>>> import pycmarkgfm
>>> pycmarkgfm.markdown_to_html('<img src="#">')
'<!-- raw HTML omitted -->\n'
```

Is there a way to show embedded HTML as it is? Thanks!

**Comment by izgzhen** [comment]
```
from pycmarkgfm import _cmark

pycmarkgfm.markdown_to_html('<img src="#">', options=_cmark.lib.CMARK_OPT_UNSAFE)
```

Seems working.

**Comment by zopieux** [comment]
Thanks for reporting. You indeed need to use cmark option. To make things slightly cleaner (this private package is not supposed to be used directly), I've introduced v1.1.0 with an `options` module with aliases and documentation, as well as some tests. See [Options in README](/Zopieux/pycmarkgfm/#options).

Version 1.1.0 was pushed to PyPi minutes ago. Enjoy!
