### ISSUE TITLE
Exposing node accessors

### ISSUE THREAD

**Issue by wagnerflo** [zopieux/pycmarkgfm#2]
Hey there,

while searching for a way to turn Markdown/Commonmark/GFM into a JSON representation (something like [mdast](https://github.com/syntax-tree/mdast) preferably) I came across your library.

You've already exposed the tree iteration functions so only the [node accessors](https://man.archlinux.org/man/cmark-gfm.3.en#Accessors) (like `cmark_node_get_literal`, `cmark_node_get_heading_level` and so on) are missing to make this easily possible.

Before putting in the work to implement this would you accept a pull request for that and are you planing to continue maintenance of this library or should I rather direct my inquiry at [theacodes/cmarkgfm](https://github.com/theacodes/cmarkgfm)?

**Comment by zopieux** [comment]
Sounds good. I see you've already inquired cmarkgfm, so feel free to open your PR wherever you prefer – including both projects. Compatibility should be trivial anyway. Thanks!

**Comment by tejasvi** [comment]
This will be very useful since currently there is no python parser which provides ast to source location map. I am firing up nodejs just to get markdown ast from remark-parse over rpc.

**Comment by wagnerflo** [comment]
I'm sorry to say I will not be working on this. I'm leaving the employer that would have sponsored this work and personally currently have no use for it.
