### ISSUE TITLE
Add support for Windows builds or provide binary win32/64 wheels

### ISSUE THREAD

**Issue by 741148263** [zopieux/pycmarkgfm#3]
![image](https://github.com/zopieux/pycmarkgfm/assets/58420844/528157ea-c62f-4a33-8199-9571f0322de3)

The above exception is consistently thrown during the installation of pycmarkgfm.What third party libraries do I need to install on windows?

Thank you very much!!!

**Comment by zopieux** [comment]
This project specifically does not officially support Windows builds, but it looks like it could work out of the box if you install it in a mingw32 context. Feel free to contribute a PR if you manage to get it working with msvc.

**Comment by 741148263** [comment]
I will give it a try, not sure if I can succeed

**Comment by 741148263** [comment]
Sorry, I can't use it on windows. I don't know enough about mingw32 to use it on a deeper level. I tried changing the default compiler to mingw32 and that didn't work either.

**Comment by zopieux** [comment]
I ended up trying out building wheels for Windows in a branch. It seems to be working just fine, so I'll upload these to PyPi sometime this week. You can try one of the attached "wheels" (remove the `.zip` extension (forced by GitHub) then `pip install your_architecture.whl`, you most likely want the amd64 version) on your machine and report whether it works!

- [pycmarkgfm-1.2.1-cp311-cp311-win_amd64.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330769/pycmarkgfm-1.2.1-cp311-cp311-win_amd64.whl.zip)
- [pycmarkgfm-1.2.1-cp311-cp311-win32.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330770/pycmarkgfm-1.2.1-cp311-cp311-win32.whl.zip)
- [pycmarkgfm-1.2.1-cp310-cp310-win_amd64.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330771/pycmarkgfm-1.2.1-cp310-cp310-win_amd64.whl.zip)
- [pycmarkgfm-1.2.1-cp310-cp310-win32.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330772/pycmarkgfm-1.2.1-cp310-cp310-win32.whl.zip)
- [pycmarkgfm-1.2.1-cp39-cp39-win_amd64.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330773/pycmarkgfm-1.2.1-cp39-cp39-win_amd64.whl.zip)
- [pycmarkgfm-1.2.1-cp39-cp39-win32.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330774/pycmarkgfm-1.2.1-cp39-cp39-win32.whl.zip)
- [pycmarkgfm-1.2.1-cp38-cp38-win_amd64.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330775/pycmarkgfm-1.2.1-cp38-cp38-win_amd64.whl.zip)
- [pycmarkgfm-1.2.1-cp38-cp38-win32.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330776/pycmarkgfm-1.2.1-cp38-cp38-win32.whl.zip)
- [pycmarkgfm-1.2.1-cp37-cp37m-win_amd64.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330777/pycmarkgfm-1.2.1-cp37-cp37m-win_amd64.whl.zip)
- [pycmarkgfm-1.2.1-cp37-cp37m-win32.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330778/pycmarkgfm-1.2.1-cp37-cp37m-win32.whl.zip)
- [pycmarkgfm-1.2.1-cp36-cp36m-win_amd64.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330779/pycmarkgfm-1.2.1-cp36-cp36m-win_amd64.whl.zip)
- [pycmarkgfm-1.2.1-cp36-cp36m-win32.whl.zip](https://github.com/zopieux/pycmarkgfm/files/12330780/pycmarkgfm-1.2.1-cp36-cp36m-win32.whl.zip)

**Comment by 741148263** [comment]
OK OK, I'll try it later. Thanks.

**Comment by 741148263** [comment]
I have successfully installed pycmarkgfm on win11 through whl. This issue can be closed! Thanks

**Comment by zopieux** [comment]
OK, https://github.com/zopieux/pycmarkgfm/actions/runs/5913153604 successfully published v1.2.1 on PyPi, with Windows, MacOS and Linux wheels. :tada:
